### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by sricc** [Urigo/angular-spinkit#20]
Would be great if this could be published to npm, with "main" defined in the package.json, for people using browersify!  Thanks.

**Comment by Urigo** [comment]
@sricc sure, do you mind pull requesting to add the file?

**Comment by sricc** [comment]
@Urigo sure, no problem will do it shortly

**Comment by sricc** [comment]
@Urigo https://github.com/Urigo/angular-spinkit/pull/22

**Comment by Urigo** [comment]
@sricc thanks, anything else I should do?

**Comment by sricc** [comment]
@Urigo If you could just publish to npm that would rock!  Thanks.

**Comment by Urigo** [comment]
done:
https://www.npmjs.com/package/angular-spinkit

**Comment by sricc** [comment]
Thanks @Urigo appreciate it!
