### ISSUE TITLE
Centered spinner

### ISSUE THREAD

**Issue by ArieVanE** [Urigo/angular-spinkit#23]
It's unclear to me how to have the spinner centered on the absolute middle of the page.

I tried to put the directive into a div, which I then center through CSS, but that has no effect at all.

How to accomplish this?

**Comment by cleor41** [comment]
I placed it inside of my topmost level div that has height and width set to 100%. I changed it's position to fixed and then centered it accordingly. top: 50%, left: 50% etc. http://stackoverflow.com/questions/2005954/center-element-with-positionfixed

**Comment by cleor41** [comment]
It actually doesn't matter if its in a 100% div or not but heres the styling I placed on the spinner directive (in my case the double-bounce-spinner.

	position: fixed;
	left: 50%;
	top: 50%;
	z-index: 10000;
	margin-top: -120px;
	margin-left: -20px;

Where the margin is tailored to the spinner.

**Comment by Urigo** [comment]
thanks @cleor41 
closing
